/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package daw;

import java.util.Random;
import javax.swing.JOptionPane;
import daw.Users;
import java.util.Map;

/**
 *
 * @author khalid
 */
public class RegistroDialogo extends javax.swing.JDialog {
    
    
    private VentanaPrincipal padre;
    
    
    /**
     * Creates new form RegistroDialogo
     */
    public RegistroDialogo(VentanaPrincipal ventana, boolean modal) {
        super(ventana, modal);
        padre = ventana;
        initComponents();
        this.setTitle("Registro");
        
    }
    
    
    
    
    //por defecto le pondremos 8 caracteres
//    private static String reemplazarContra(int length) {
//        String characters = "abcdefghijklmnopqrstuvwxyz";
//        Random random = new Random();
//        String aleatorio = "";
//        for (int i = 0; i < length; i++) {
//            char randomChar = characters.charAt(random.nextInt(characters.length()));
//            aleatorio += randomChar;
//        }
//        return aleatorio;
//        
//    }
//    
//    
//    
//    private void cambiarContra(){
//        String aux=reemplazarContra(8);
//        ContraseñaRegistroTexto.setText(aux);
//        ContraseñaConfirmRegistroTexto.setText(aux);
//        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuarioRegistro = new javax.swing.JLabel();
        ContraseñaRegistro = new javax.swing.JLabel();
        ContraseñaConfirmRegistro = new javax.swing.JLabel();
        mostrarContraseña = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        ContraseñaRegistroTexto = new javax.swing.JPasswordField();
        ContraseñaConfirmRegistroTexto = new javax.swing.JPasswordField();
        UsuarioRegistroTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        UsuarioRegistro.setText("Usuario");

        ContraseñaRegistro.setText("Contraseña");

        ContraseñaConfirmRegistro.setText("Confirmacion Contraseña");

        mostrarContraseña.setText("Ver/Ocultar Contraseñas");
        mostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContraseñaActionPerformed(evt);
            }
        });

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mostrarContraseña)
                        .addGap(37, 37, 37)
                        .addComponent(Registrar)
                        .addGap(51, 51, 51)
                        .addComponent(Cancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ContraseñaRegistroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ContraseñaConfirmRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContraseñaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UsuarioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addComponent(ContraseñaConfirmRegistroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(UsuarioRegistroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioRegistro)
                    .addComponent(UsuarioRegistroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaRegistro)
                    .addComponent(ContraseñaRegistroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaConfirmRegistro)
                    .addComponent(ContraseñaConfirmRegistroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarContraseña)
                    .addComponent(Registrar)
                    .addComponent(Cancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void mostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContraseñaActionPerformed
        // TODO add your handling code here:
        if (ContraseñaRegistroTexto.echoCharIsSet() && ContraseñaConfirmRegistroTexto.echoCharIsSet()) {
            // Muestra la contraseña poniendole los caracteres naturales
            ContraseñaRegistroTexto.setEchoChar((char) 0);
            ContraseñaConfirmRegistroTexto.setEchoChar((char) 0);

        } else {
            // Oculta la contraseña poniendole de nuevo los caracteres *
            ContraseñaRegistroTexto.setEchoChar('*');
            ContraseñaConfirmRegistroTexto.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarContraseñaActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:

        if (!(ContraseñaConfirmRegistroTexto.getText()
                .equalsIgnoreCase(ContraseñaRegistroTexto
                        .getText()))) {
            JOptionPane.showMessageDialog(null,
                    "Las contraseñas no son iguales repite de nuevo el proceso");

            ContraseñaConfirmRegistroTexto.setText(null);
            ContraseñaRegistroTexto.setText(null);

        }

//        if (ContraseñaConfirmRegistroTexto.getText()
//                .equals(ContraseñaRegistroTexto
//                        .getText()) && 
//                (!(Users.leerUsuariosDesdeCSV().containsKey
//        (UsuarioRegistroTexto)))
//                && (!(Users.leerUsuariosDesdeCSV()
//                .containsValue(ContraseñaRegistroTexto)))) 
//        {
//            Users.escribirNuevoUser(UsuarioRegistroTexto.getText(),
//                    ContraseñaRegistroTexto.getText());
//        }
        
        if (ContraseñaConfirmRegistroTexto.getText()
                .equals(ContraseñaRegistroTexto
                        .getText())) {
            
            Map <String,String> mapeado = Users.leerUsuariosDesdeCSV();
                    mapeado.put(UsuarioRegistroTexto.getText(), ContraseñaRegistroTexto.getText());
            Users.escribirNuevoUser(mapeado);
        }
        
        
        
    }//GEN-LAST:event_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistroDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistroDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistroDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistroDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                RegistroDialogo dialog = new RegistroDialogo(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel ContraseñaConfirmRegistro;
    private javax.swing.JPasswordField ContraseñaConfirmRegistroTexto;
    private javax.swing.JLabel ContraseñaRegistro;
    private javax.swing.JPasswordField ContraseñaRegistroTexto;
    private javax.swing.JButton Registrar;
    private javax.swing.JLabel UsuarioRegistro;
    private javax.swing.JTextField UsuarioRegistroTexto;
    private javax.swing.JButton mostrarContraseña;
    // End of variables declaration//GEN-END:variables
}
